<html>
  <head>
    <style>
      body{
        background-image: url(https://gcdnb.pbrd.co/images/vKHLFqDBQKE1.gif?o=1);
        backround-repeat: no-repeat;
        backround-size: cover;
      }
    </style>
    
  </head>
  <body>
    
  </body>
</html>
